import "./globals.css";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme";
import { QueryProvider } from "@/providers/query-provider";
import { Provider } from "jotai";
import type { Metadata } from "next";

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
});

export const metadata: Metadata = {
    title: "Rest Api Countries",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={cn(
                    "min-h-screen bg-background font-sans antialiased",
                    fontSans.variable
                )}
            >
                <QueryProvider>
                    <Provider>
                        <ThemeProvider attribute="class" defaultTheme="system">
                            {children}
                        </ThemeProvider>
                    </Provider>
                </QueryProvider>
            </body>
        </html>
    );
}
